// AUTO-GENERATED by scripts/gen-spec.js from *.openapi.js declarations.
// Do not edit by hand. CI will reject manual changes via `npm run spec:check`.

const Joi = require('joi');

module.exports = {
  'Taxes': {
    create: Joi.object({
    taxName: Joi.string().required(),
    taxValue: Joi.string().required(),
    isDefault: Joi.boolean(),
    enabled: Joi.boolean(),
    }).options({ stripUnknown: false, allowUnknown: false }),
    update: Joi.object({
    taxName: Joi.string(),
    taxValue: Joi.string(),
    isDefault: Joi.boolean(),
    enabled: Joi.boolean(),
    }).options({ stripUnknown: false, allowUnknown: false }),
  },
};
